version: '3'
services:
  database:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "35698:3306"
    networks:
      - orchard
  # api:
  #   container_name: api
  #   build: ./api
  #   networks:
  #     - orchard
  #   depends_on:
  #     - database
  #   restart: on-failure:5
  #   volumes:
  #     - ./api:/api

  website:
    container_name: website
    build: ./website
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - orchard
    volumes:
      - ./website:/app
  
networks:
  orchard:
    driver: bridge
